/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_whtmltopdf_WKHtmlPDFConverter */

#ifndef _Included_org_swdc_whtmltopdf_WKHtmlPDFConverter
#define _Included_org_swdc_whtmltopdf_WKHtmlPDFConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_whtmltopdf_WKHtmlPDFConverter
 * Method:    generatePDF
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_whtmltopdf_WKHtmlPDFConverter_generatePDF
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
